site_name: danalyzer documentation
site_author: 'Dan Denis'
docs_dir: docs/
repo_name: 'ddenis73/danalyzer-docs'
repo_url: 'https://github.com/ddenis73/danalyzer-docs'
site_url: 'https://github.com/ddenis73/danalyzer-docs/'

pages:
  - Home: 'index.md'
  - Tutorials:
    - MATLAB: 
      - Overview: 'matlab-tutorial.md'
      - MATLAB environment: 'matlab-environment.md'
      - Variables: 'matlab-variables.md'
      - Indexing: 'matlab-indexing.md'
      - Functions: 'matlab-functions.md'
      - Control statements: 'matlab-control-statements.md'
      - Importing/exporting: 'matlab-import-export.md'
      - Plotting: 'matlab-plotting.md'
    - GUI: 'gui-tutorial.md'
    - Tools: 'tools-tutorial.md'
  - Vignettes: 'vignettes.md'
  - Reference: 'reference.md'

theme:
  name: material
  palette: 
    - scheme: default
      primary: deep orange
      accent: deep purple

markdown_extensions:
    - attr_list
    - admonition
