site_name: danalyzer documentation
site_author: 'Dan Denis'
docs_dir: docs/
repo_name: 'ddenis73/danalyzer-docs'
repo_url: 'https://github.com/ddenis73/danalyzer-docs'
site_url: 'https://github.com/ddenis73/danalyzer-docs/'

pages:
  - Home: 'index.md'
  - Quickstart: 'gui-tutorial.md'
  - Reference:
    - GUI:
      - Loading data: 'gui-load-data.md'
      - Data browsing: 'gui-data-browser.md'
      - Sleep scoring: 'gui-sleep-scoring.md'
      - Sleep statistics: 'gui-sleep-statistics.md'
      - Sleep scorer reliability: 'gui-reliability.md'
      - Artifact rejection: 'gui-artifact-rejection.md'
      - Marking segments: 'gui-segment-marker.md'
      - Custom notations: 'gui-event-marker.md'
      - Channel properties: 'gui-channel-properties.md'
      - Subsetting data: 'gui-subset-data.md'
      - Saving data: 'gui-save-data.md'
      - Montage creation: 'gui-montage.md'
      - File format information: 'gui-file-formats.md'
      - Import/export different file types: 'gui-import-export.md'
      - Calling danalyzer from command window: 'gui-command-window.md'

theme:
  name: material
  palette: 
    - scheme: default
      primary: deep orange
      accent: deep purple

markdown_extensions:
    - attr_list
    - admonition
